name: "career-seekers"
services:
  fs-postgres:
    container_name: fs-postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${FS_DB_USER}
      POSTGRES_PASSWORD: ${FS_DB_PASSWORD}
    volumes:
      - fs-postgres-data:/var/lib/postgresql/data
    ports:
      - "8294:5432"
    networks:
      - backend-net

volumes:
  fs-postgres-data:

networks:
  backend-net:
    driver: bridge