package org.careerseekers.csfileservice.enums

enum class FileTypes {
    AVATAR,
    SNILS,
    STUDYING_CERTIFICATE,
    ADDITIONAL_STUDYING_CERTIFICATE,
    CONSENT_TO_CHILD_PDP,
    CONSENT_TO_MENTOR_PDP,
    CONSENT_TO_TUTOR_PDP,
    CONSENT_TO_EXPERT_PDP,
    BIRTH_CERTIFICATE,
    DIRECTION_ICON,
    TASK,
    CRITERIA,
    STATEMENT,
    FINAL_TASK,
    FINAL_CRITERIA,
    FINAL_STATEMENT,
    DESCRIPTION,
}